project:
  type: website

website:
  title: "The Sam Kasten Legacy Project"
  navbar:
    search: true
    left:
      - href: ./index.qmd
        text: Home
      - href: ./about_sam.qmd
        text: About Sam
      - href: ./memoirs.qmd
        text: Memoirs
      - href: ./articles/index.qmd
        text: Articles

      

format:
  html:
    theme: cosmo
    toc: true



