project:
  type: website

website:
  announcement:
    icon: exclamation-circle
    dismissable: true
    content: "**URLs have changed!** Memoirs are now available from [https://sjspielman.github.io/sam-kasten-memoirs](https://sjspielman.github.io/sam-kasten-memoirs)."
    type: info
  title: "The Sam Kasten Legacy Project"
  navbar:
    search: true
    left:
      - text: Home
        href: ./index.qmd
        
      - text: About Sam
        href: ./about-sam.qmd
        
      - text: Memoirs
        href: ./memoirs.qmd
        
      - text: Articles
        menu: 
          - text: Birthdays
            href: ./articles/birthdays.qmd
          - text: Miscellany
            href: ./articles/miscellany.qmd
             
        
  page-footer: |
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'
  google-analytics: "G-6PYMFW4V7E"

  
format:
  html:
    theme: cosmo
    toc: true



