# {{< var sam-full >}} -- the Yiddish Broadway actor on Second Avenue

> He was the first to bring Broadway sensibility to the Yiddish stage. -- The actor who is always young and joyful even though his hair is already white.

[Translator's note: Throughout this article, there are several English phrases written in transliterated Yiddish. I have italicized these phrases to indicate they were indeed written "in English."]


A dance, a jump - _that's all_!

That's how {{< var sam-full >}} danced his way through his little world for 65 years, and in his dancing and jumping on Second Avenue, people see him move with the same ease as you'd expect to see on the Broadway stage. 

Yes, from Broadway. {{< var kestin >}} was the first to bring a Broadway sensibility to the Yiddish stage. His couplets included _"Fifty-fifty"_, _"The line is busy_", _"A mistake"_. He felt that we needed to attract an English-speaking audience to the Yiddish stage. He already felt this way 70 years ago.

I don't mean to say that {{< var kestin >}} was someone who copied American actors, because his best roles were all true Jewish types - _chasidishe_, enthusiastically-Jewish characters, but the Jewish East Side^[Lower East Side, NYC] which has yearned for Broadway comedians because they are strangers to the East Side, has long seen {{< var kestin >}} as a comedia "ala Broadway."

Every writer, composter, sculpture, follows a well-known artist from an earlier era. In the art world, people say that someone belongs to such-and-such school. For example in the literary world, people say, "He is a classical writer." In the music world, "he belongs to the Wagner school." In the painting world, "he belongs to the Rembrandt school," and so on and so forth.

Actors too have schools. They don't copy, but follow in someone else's the footsteps. {{< var sam-full >}} takes after {{< var mogu-full >}}. He always imitates {{< var mogu >}}'s little dances and their little idiosyncracies, but in a {{< var kestin >}}-esque sort of way. {{< var mogu >}} himself actually pointed this out - three days before his death, I went to visit {{< var mogu >}}, and feeling like this was perhaps the last time I would speak to him, I asked:

"Mr. {{< var mogu >}}, why don't Yiddish actors copy you? Comedians make an attempt to copy [Bernstein](https://www.museumoffamilyhistory.com/yt/lex/B/bernstein-berl.htm), Torenbergen^[I am unable to find a reference for this person: טאָרענבערען] (a comedian from the earliest days in America). But nobody copies you."

{{< var mogu >}} answered my quietly, with his "{{< var mogu-full >}} smile:"

"{{< var sam-full >}} copies me, and so very well. But when {{< var sam-full >}} copies me, I suddenly transform into a Broadway actor."

And that's {{< var sam-full >}}.

When he isn't performing, people see him going around in his {{< var sam-kestin >}}-esque manner. His vibe attracts the American youth to the Yiddish stage, and successfully too. 

My son, who is already a young man of 30 used to copy {{< var kestin >}} - he'd talk like him, sing like him, walk, dance, and even eat and sleep with {{< var sam-full >}}'s songs on his lips.

only one samples